version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      # copy the sql script to create tables
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql